Merge karnage/dev to main
cpp-gamedev/blog pull request #13
Opened 2021-04-01 06:13 UTC by karnkaul

2021-04-01 12:08 UTC, hentai-chan requested changes

2021-04-01 12:08 UTC, hentai-chan commented on content/series/101/2_development_environment/index.md
> +Since C++ standards are generally very meticulous about backwards compatibility, not-so-great language and library design decisions made in the past cannot easily be rectified through breaking change
> Ergo, there are a few language potholes and traps where the compiler can only warn you - cannot issue an error and stop (unless you configure it to be that way for a specific set of / all warnings), and which is why modern C++ development is greatly aided by turning up compiler warnings and using linters that perform static analysis outside compilation (perhaps even risking some false positive warnings).

This is a very long sentence. Your text is more accessible for non-native speakers and younger readers if you break it up a little. For example:

_Ergo, there are a few language potholes and traps where the compiler can only issue warnings for you unless you configure the compiler to interpret (all) warnings as errors. Modern C++ development is greatly aided by turning up compiler warnings and using linters that perform static analysis outside compilation, though this practice sometimes risks false positives._

> [...] to set at least the following __options__ for every [...]

2021-04-01 12:08 UTC, hentai-chan commented on content/series/101/2_development_environment/index.md
> +The core idea behind debugging is to spin off a command line task: `cmake --build <output_dir>` which can be invoked by some keyboard shortcut via the text editor. Debugging is a bit more involved, t
> The core idea behind debugging is to spin off a command line task: `cmake --build <output_dir>` which can be invoked by some keyboard shortcut via the text editor.

Use different punctuation to guide the reading flow:

Better: _The core idea behind debugging is to spin off a command line task (`cmake --build <output_dir>`) which can be invoked by some keyboard shortcut via the text editor._

2021-04-01 23:42 UTC, karnkaul commented on content/series/101/2_development_environment/index.md
> +Most C++ programmers spend a considerable amount of time meticulously formatting their precious code, until they make an acquaintance with an autoformatter - of which `clang-format` is the indisputed
Here `reams` means "bunch of printing paper", is just a lame metaphor. 😛

2021-04-02 20:56 UTC, hentai-chan approved these changes
Well done! 💮

2021-04-03 01:29 UTC, merged